/**
 * Demo seed data — 3 students with full semester history.
 * Loaded via the "Load Demo Data" button on the dashboard.
 */
import { Student } from '@/types/student';

export const DEMO_STUDENTS: Student[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. Arjun Sharma — CSE, 6 sems, high achiever, improving trend
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'demo-student-001',
    name: 'Arjun Sharma',
    rollNumber: 'CSE21001',
    department: 'Computer Science & Engineering',
    program: 'B.Tech',
    batch: '2021–2025',
    email: 'arjun.sharma@demo.edu',
    phone: '9876543210',
    university: 'Anna University',
    avatarColor: '#6366f1',
    currentSemester: 6,
    currentCGPA: 8.87,
    createdAt: '2024-01-10T09:00:00.000Z',
    updatedAt: '2024-12-01T09:00:00.000Z',
    semesters: [
      {
        id: 'sem-001-1',
        semesterNumber: 1,
        academicYear: '2021–22',
        session: 'odd',
        sgpa: 8.20,
        cgpaAfterSemester: 8.20,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 88,
        attendance: [
          { month: 'Aug', percentage: 90, classesHeld: 30, classesAttended: 27 },
          { month: 'Sep', percentage: 86, classesHeld: 32, classesAttended: 27 },
          { month: 'Oct', percentage: 88, classesHeld: 28, classesAttended: 25 },
          { month: 'Nov', percentage: 87, classesHeld: 26, classesAttended: 23 },
        ],
        subjects: [
          { id: 's1-1', code: 'MA1101', name: 'Engineering Mathematics I', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 90, category: 'core' },
          { id: 's1-2', code: 'PH1101', name: 'Engineering Physics', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 88, category: 'core' },
          { id: 's1-3', code: 'CS1101', name: 'Programming in C', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 92, category: 'core' },
          { id: 's1-4', code: 'CS1102', name: 'Programming Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 95, category: 'lab' },
          { id: 's1-5', code: 'EN1101', name: 'Technical English', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 85, category: 'elective' },
          { id: 's1-6', code: 'EE1101', name: 'Basic Electrical Engineering', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 87, category: 'core' },
        ],
      },
      {
        id: 'sem-001-2',
        semesterNumber: 2,
        academicYear: '2021–22',
        session: 'even',
        sgpa: 8.55,
        cgpaAfterSemester: 8.38,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 91,
        attendance: [
          { month: 'Jan', percentage: 92, classesHeld: 30, classesAttended: 28 },
          { month: 'Feb', percentage: 90, classesHeld: 30, classesAttended: 27 },
          { month: 'Mar', percentage: 89, classesHeld: 28, classesAttended: 25 },
          { month: 'Apr', percentage: 93, classesHeld: 25, classesAttended: 23 },
        ],
        subjects: [
          { id: 's2-1', code: 'MA1201', name: 'Engineering Mathematics II', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 93, category: 'core' },
          { id: 's2-2', code: 'CS1201', name: 'Data Structures', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 95, category: 'core' },
          { id: 's2-3', code: 'CS1202', name: 'Digital Logic', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 89, category: 'core' },
          { id: 's2-4', code: 'CS1203', name: 'Data Structures Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 96, category: 'lab' },
          { id: 's2-5', code: 'EN1201', name: 'Professional Communication', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 86, category: 'elective' },
          { id: 's2-6', code: 'PH1201', name: 'Engineering Chemistry', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 91, category: 'core' },
        ],
      },
      {
        id: 'sem-001-3',
        semesterNumber: 3,
        academicYear: '2022–23',
        session: 'odd',
        sgpa: 8.70,
        cgpaAfterSemester: 8.48,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 89,
        attendance: [
          { month: 'Aug', percentage: 91, classesHeld: 30, classesAttended: 27 },
          { month: 'Sep', percentage: 87, classesHeld: 30, classesAttended: 26 },
          { month: 'Oct', percentage: 90, classesHeld: 28, classesAttended: 25 },
          { month: 'Nov', percentage: 88, classesHeld: 26, classesAttended: 23 },
        ],
        subjects: [
          { id: 's3-1', code: 'CS2101', name: 'Object Oriented Programming', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 94, category: 'core' },
          { id: 's3-2', code: 'CS2102', name: 'Computer Organization', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 90, category: 'core' },
          { id: 's3-3', code: 'MA2101', name: 'Discrete Mathematics', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 87, category: 'core' },
          { id: 's3-4', code: 'CS2103', name: 'OOP Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 95, category: 'lab' },
          { id: 's3-5', code: 'CS2104', name: 'Database Management Systems', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 88, category: 'core' },
          { id: 's3-6', code: 'CS2105', name: 'Operating Systems', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 85, category: 'core' },
          { id: 's3-7', code: 'CS2106', name: 'DBMS Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 93, category: 'lab' },
        ],
      },
      {
        id: 'sem-001-4',
        semesterNumber: 4,
        academicYear: '2022–23',
        session: 'even',
        sgpa: 8.90,
        cgpaAfterSemester: 8.59,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 93,
        attendance: [
          { month: 'Jan', percentage: 94, classesHeld: 30, classesAttended: 28 },
          { month: 'Feb', percentage: 91, classesHeld: 30, classesAttended: 27 },
          { month: 'Mar', percentage: 93, classesHeld: 28, classesAttended: 26 },
          { month: 'Apr', percentage: 94, classesHeld: 25, classesAttended: 23 },
        ],
        subjects: [
          { id: 's4-1', code: 'CS2201', name: 'Algorithm Design & Analysis', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 96, category: 'core' },
          { id: 's4-2', code: 'CS2202', name: 'Computer Networks', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 93, category: 'core' },
          { id: 's4-3', code: 'CS2203', name: 'Software Engineering', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 91, category: 'core' },
          { id: 's4-4', code: 'CS2204', name: 'Networks Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 97, category: 'lab' },
          { id: 's4-5', code: 'MA2201', name: 'Probability & Statistics', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 90, category: 'core' },
          { id: 's4-6', code: 'CS2205', name: 'Microprocessors', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 92, category: 'core' },
          { id: 's4-7', code: 'CS2206', name: 'Microprocessors Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 95, category: 'lab' },
        ],
      },
      {
        id: 'sem-001-5',
        semesterNumber: 5,
        academicYear: '2023–24',
        session: 'odd',
        sgpa: 9.10,
        cgpaAfterSemester: 8.69,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 92,
        attendance: [
          { month: 'Aug', percentage: 93, classesHeld: 30, classesAttended: 28 },
          { month: 'Sep', percentage: 90, classesHeld: 30, classesAttended: 27 },
          { month: 'Oct', percentage: 93, classesHeld: 28, classesAttended: 26 },
          { month: 'Nov', percentage: 92, classesHeld: 26, classesAttended: 24 },
        ],
        subjects: [
          { id: 's5-1', code: 'CS3101', name: 'Machine Learning', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 95, category: 'elective' },
          { id: 's5-2', code: 'CS3102', name: 'Web Technologies', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 93, category: 'core' },
          { id: 's5-3', code: 'CS3103', name: 'Compiler Design', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 90, category: 'core' },
          { id: 's5-4', code: 'CS3104', name: 'ML Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 96, category: 'lab' },
          { id: 's5-5', code: 'CS3105', name: 'Cloud Computing', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 92, category: 'elective' },
          { id: 's5-6', code: 'CS3106', name: 'Information Security', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 88, category: 'core' },
          { id: 's5-7', code: 'CS3107', name: 'Web Tech Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 94, category: 'lab' },
        ],
      },
      {
        id: 'sem-001-6',
        semesterNumber: 6,
        academicYear: '2023–24',
        session: 'even',
        sgpa: 9.30,
        cgpaAfterSemester: 8.87,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 94,
        attendance: [
          { month: 'Jan', percentage: 95, classesHeld: 30, classesAttended: 28 },
          { month: 'Feb', percentage: 93, classesHeld: 30, classesAttended: 28 },
          { month: 'Mar', percentage: 94, classesHeld: 28, classesAttended: 26 },
          { month: 'Apr', percentage: 95, classesHeld: 25, classesAttended: 24 },
        ],
        subjects: [
          { id: 's6-1', code: 'CS3201', name: 'Deep Learning', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 96, category: 'elective' },
          { id: 's6-2', code: 'CS3202', name: 'Distributed Systems', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 95, category: 'core' },
          { id: 's6-3', code: 'CS3203', name: 'Big Data Analytics', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 92, category: 'elective' },
          { id: 's6-4', code: 'CS3204', name: 'Project Work Phase I', credits: 4, grade: 'O', gradePoint: 10, attendancePercentage: 98, category: 'project' },
          { id: 's6-5', code: 'CS3205', name: 'Natural Language Processing', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 93, category: 'elective' },
          { id: 's6-6', code: 'CS3206', name: 'Mobile Application Dev', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 94, category: 'lab' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. Priya Nair — ECE, 5 sems, consistent mid-range, attendance dip in sem 4
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'demo-student-002',
    name: 'Priya Nair',
    rollNumber: 'ECE21045',
    department: 'Electronics & Communication Engineering',
    program: 'B.Tech',
    batch: '2021–2025',
    email: 'priya.nair@demo.edu',
    phone: '9876500001',
    university: 'Anna University',
    avatarColor: '#ec4899',
    currentSemester: 5,
    currentCGPA: 7.65,
    createdAt: '2024-01-10T09:30:00.000Z',
    updatedAt: '2024-12-01T09:30:00.000Z',
    semesters: [
      {
        id: 'sem-002-1',
        semesterNumber: 1,
        academicYear: '2021–22',
        session: 'odd',
        sgpa: 7.80,
        cgpaAfterSemester: 7.80,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 85,
        attendance: [
          { month: 'Aug', percentage: 87, classesHeld: 30, classesAttended: 26 },
          { month: 'Sep', percentage: 84, classesHeld: 32, classesAttended: 27 },
          { month: 'Oct', percentage: 83, classesHeld: 28, classesAttended: 23 },
          { month: 'Nov', percentage: 86, classesHeld: 26, classesAttended: 22 },
        ],
        subjects: [
          { id: 'p1-1', code: 'MA1101', name: 'Engineering Mathematics I', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 87, category: 'core' },
          { id: 'p1-2', code: 'PH1101', name: 'Engineering Physics', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 85, category: 'core' },
          { id: 'p1-3', code: 'EC1101', name: 'Circuit Theory', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 86, category: 'core' },
          { id: 'p1-4', code: 'EC1102', name: 'Electronics Lab', credits: 2, grade: 'A+', gradePoint: 9, attendancePercentage: 90, category: 'lab' },
          { id: 'p1-5', code: 'EN1101', name: 'Technical English', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 82, category: 'elective' },
          { id: 'p1-6', code: 'EE1101', name: 'Basic Electrical Engineering', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 83, category: 'core' },
        ],
      },
      {
        id: 'sem-002-2',
        semesterNumber: 2,
        academicYear: '2021–22',
        session: 'even',
        sgpa: 7.60,
        cgpaAfterSemester: 7.70,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 82,
        attendance: [
          { month: 'Jan', percentage: 83, classesHeld: 30, classesAttended: 25 },
          { month: 'Feb', percentage: 80, classesHeld: 30, classesAttended: 24 },
          { month: 'Mar', percentage: 82, classesHeld: 28, classesAttended: 23 },
          { month: 'Apr', percentage: 84, classesHeld: 25, classesAttended: 21 },
        ],
        subjects: [
          { id: 'p2-1', code: 'MA1201', name: 'Engineering Mathematics II', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 84, category: 'core' },
          { id: 'p2-2', code: 'EC1201', name: 'Signals & Systems', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 82, category: 'core' },
          { id: 'p2-3', code: 'EC1202', name: 'Electronic Devices', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 83, category: 'core' },
          { id: 'p2-4', code: 'EC1203', name: 'Devices Lab', credits: 2, grade: 'A+', gradePoint: 9, attendancePercentage: 88, category: 'lab' },
          { id: 'p2-5', code: 'CS1201', name: 'Programming in C', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 80, category: 'core' },
          { id: 'p2-6', code: 'PH1201', name: 'Engineering Chemistry', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 78, category: 'core' },
        ],
      },
      {
        id: 'sem-002-3',
        semesterNumber: 3,
        academicYear: '2022–23',
        session: 'odd',
        sgpa: 7.90,
        cgpaAfterSemester: 7.77,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 87,
        attendance: [
          { month: 'Aug', percentage: 88, classesHeld: 30, classesAttended: 26 },
          { month: 'Sep', percentage: 86, classesHeld: 30, classesAttended: 26 },
          { month: 'Oct', percentage: 87, classesHeld: 28, classesAttended: 24 },
          { month: 'Nov', percentage: 87, classesHeld: 26, classesAttended: 23 },
        ],
        subjects: [
          { id: 'p3-1', code: 'EC2101', name: 'Digital Electronics', credits: 4, grade: 'A+', gradePoint: 9, attendancePercentage: 90, category: 'core' },
          { id: 'p3-2', code: 'EC2102', name: 'Electromagnetic Theory', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 85, category: 'core' },
          { id: 'p3-3', code: 'EC2103', name: 'Analog Circuits', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 88, category: 'core' },
          { id: 'p3-4', code: 'EC2104', name: 'Digital Lab', credits: 2, grade: 'O', gradePoint: 10, attendancePercentage: 92, category: 'lab' },
          { id: 'p3-5', code: 'CS2101', name: 'Data Structures', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 84, category: 'core' },
          { id: 'p3-6', code: 'MA2101', name: 'Probability & Random Process', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 86, category: 'core' },
          { id: 'p3-7', code: 'EC2105', name: 'Analog Lab', credits: 2, grade: 'A+', gradePoint: 9, attendancePercentage: 91, category: 'lab' },
        ],
      },
      {
        id: 'sem-002-4',
        semesterNumber: 4,
        academicYear: '2022–23',
        session: 'even',
        sgpa: 7.20,
        cgpaAfterSemester: 7.62,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 72,
        attendance: [
          { month: 'Jan', percentage: 74, classesHeld: 30, classesAttended: 22 },
          { month: 'Feb', percentage: 70, classesHeld: 30, classesAttended: 21 },
          { month: 'Mar', percentage: 71, classesHeld: 28, classesAttended: 20 },
          { month: 'Apr', percentage: 73, classesHeld: 25, classesAttended: 18 },
        ],
        subjects: [
          { id: 'p4-1', code: 'EC2201', name: 'Communication Systems', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 75, category: 'core' },
          { id: 'p4-2', code: 'EC2202', name: 'VLSI Design', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 72, category: 'core' },
          { id: 'p4-3', code: 'EC2203', name: 'Microprocessors', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 69, category: 'core' },
          { id: 'p4-4', code: 'EC2204', name: 'Communication Lab', credits: 2, grade: 'A', gradePoint: 8.5, attendancePercentage: 78, category: 'lab' },
          { id: 'p4-5', code: 'CS2201', name: 'Computer Networks', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 70, category: 'core' },
          { id: 'p4-6', code: 'EC2205', name: 'Control Systems', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 68, category: 'core' },
          { id: 'p4-7', code: 'EC2206', name: 'Microprocessors Lab', credits: 2, grade: 'A', gradePoint: 8.5, attendancePercentage: 76, category: 'lab' },
        ],
      },
      {
        id: 'sem-002-5',
        semesterNumber: 5,
        academicYear: '2023–24',
        session: 'odd',
        sgpa: 7.80,
        cgpaAfterSemester: 7.65,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 84,
        attendance: [
          { month: 'Aug', percentage: 85, classesHeld: 30, classesAttended: 25 },
          { month: 'Sep', percentage: 83, classesHeld: 30, classesAttended: 25 },
          { month: 'Oct', percentage: 84, classesHeld: 28, classesAttended: 23 },
          { month: 'Nov', percentage: 85, classesHeld: 26, classesAttended: 22 },
        ],
        subjects: [
          { id: 'p5-1', code: 'EC3101', name: 'Digital Signal Processing', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 86, category: 'core' },
          { id: 'p5-2', code: 'EC3102', name: 'Wireless Communication', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 84, category: 'elective' },
          { id: 'p5-3', code: 'EC3103', name: 'Embedded Systems', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 85, category: 'core' },
          { id: 'p5-4', code: 'EC3104', name: 'DSP Lab', credits: 2, grade: 'A+', gradePoint: 9, attendancePercentage: 90, category: 'lab' },
          { id: 'p5-5', code: 'EC3105', name: 'IoT & Sensors', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 82, category: 'elective' },
          { id: 'p5-6', code: 'EC3106', name: 'Antenna & Wave Propagation', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 79, category: 'core' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. Ravi Kumar — IT, 4 sems, declining trend, 1 backlog cleared, low attendance
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'demo-student-003',
    name: 'Ravi Kumar',
    rollNumber: 'IT21088',
    department: 'Information Technology',
    program: 'B.Tech',
    batch: '2021–2025',
    email: 'ravi.kumar@demo.edu',
    phone: '9876599999',
    university: 'Anna University',
    avatarColor: '#f59e0b',
    currentSemester: 4,
    currentCGPA: 6.42,
    createdAt: '2024-01-10T10:00:00.000Z',
    updatedAt: '2024-12-01T10:00:00.000Z',
    semesters: [
      {
        id: 'sem-003-1',
        semesterNumber: 1,
        academicYear: '2021–22',
        session: 'odd',
        sgpa: 7.20,
        cgpaAfterSemester: 7.20,
        totalCredits: 22,
        earnedCredits: 22,
        backlogs: 0,
        overallAttendance: 80,
        attendance: [
          { month: 'Aug', percentage: 82, classesHeld: 30, classesAttended: 25 },
          { month: 'Sep', percentage: 78, classesHeld: 32, classesAttended: 25 },
          { month: 'Oct', percentage: 80, classesHeld: 28, classesAttended: 22 },
          { month: 'Nov', percentage: 79, classesHeld: 26, classesAttended: 21 },
        ],
        subjects: [
          { id: 'r1-1', code: 'MA1101', name: 'Engineering Mathematics I', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 82, category: 'core' },
          { id: 'r1-2', code: 'PH1101', name: 'Engineering Physics', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 79, category: 'core' },
          { id: 'r1-3', code: 'IT1101', name: 'Problem Solving & Python', credits: 4, grade: 'A', gradePoint: 8.5, attendancePercentage: 84, category: 'core' },
          { id: 'r1-4', code: 'IT1102', name: 'Python Lab', credits: 2, grade: 'A+', gradePoint: 9, attendancePercentage: 88, category: 'lab' },
          { id: 'r1-5', code: 'EN1101', name: 'Technical English', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 76, category: 'elective' },
          { id: 'r1-6', code: 'EE1101', name: 'Basic Electrical Engineering', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 78, category: 'core' },
        ],
      },
      {
        id: 'sem-003-2',
        semesterNumber: 2,
        academicYear: '2021–22',
        session: 'even',
        sgpa: 6.80,
        cgpaAfterSemester: 7.00,
        totalCredits: 22,
        earnedCredits: 20,
        backlogs: 1,
        overallAttendance: 74,
        attendance: [
          { month: 'Jan', percentage: 75, classesHeld: 30, classesAttended: 22 },
          { month: 'Feb', percentage: 72, classesHeld: 30, classesAttended: 22 },
          { month: 'Mar', percentage: 73, classesHeld: 28, classesAttended: 20 },
          { month: 'Apr', percentage: 76, classesHeld: 25, classesAttended: 19 },
        ],
        subjects: [
          { id: 'r2-1', code: 'MA1201', name: 'Engineering Mathematics II', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 76, category: 'core' },
          { id: 'r2-2', code: 'IT1201', name: 'Data Structures', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 73, category: 'core' },
          { id: 'r2-3', code: 'IT1202', name: 'Digital Fundamentals', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 74, category: 'core' },
          { id: 'r2-4', code: 'IT1203', name: 'DS Lab', credits: 2, grade: 'A', gradePoint: 8.5, attendancePercentage: 80, category: 'lab' },
          { id: 'r2-5', code: 'EN1201', name: 'Professional Communication', credits: 4, grade: 'F', gradePoint: 0, attendancePercentage: 65, category: 'elective' },
          { id: 'r2-6', code: 'PH1201', name: 'Engineering Chemistry', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 72, category: 'core' },
        ],
      },
      {
        id: 'sem-003-3',
        semesterNumber: 3,
        academicYear: '2022–23',
        session: 'odd',
        sgpa: 6.50,
        cgpaAfterSemester: 6.70,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 76,
        attendance: [
          { month: 'Aug', percentage: 78, classesHeld: 30, classesAttended: 23 },
          { month: 'Sep', percentage: 75, classesHeld: 30, classesAttended: 22 },
          { month: 'Oct', percentage: 76, classesHeld: 28, classesAttended: 21 },
          { month: 'Nov', percentage: 76, classesHeld: 26, classesAttended: 20 },
        ],
        subjects: [
          { id: 'r3-1', code: 'IT2101', name: 'Object Oriented Programming', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 78, category: 'core' },
          { id: 'r3-2', code: 'IT2102', name: 'Computer Organization', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 74, category: 'core' },
          { id: 'r3-3', code: 'MA2101', name: 'Discrete Mathematics', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 75, category: 'core' },
          { id: 'r3-4', code: 'IT2103', name: 'OOP Lab', credits: 2, grade: 'A', gradePoint: 8.5, attendancePercentage: 82, category: 'lab' },
          { id: 'r3-5', code: 'IT2104', name: 'Database Management', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 77, category: 'core' },
          { id: 'r3-6', code: 'IT2105', name: 'Operating Systems', credits: 4, grade: 'P', gradePoint: 5, attendancePercentage: 70, category: 'core' },
          { id: 'r3-7', code: 'EN1201', name: 'Professional Communication', credits: 2, grade: 'B+', gradePoint: 8, attendancePercentage: 79, category: 'elective' },
        ],
      },
      {
        id: 'sem-003-4',
        semesterNumber: 4,
        academicYear: '2022–23',
        session: 'even',
        sgpa: 6.10,
        cgpaAfterSemester: 6.42,
        totalCredits: 24,
        earnedCredits: 24,
        backlogs: 0,
        overallAttendance: 70,
        attendance: [
          { month: 'Jan', percentage: 72, classesHeld: 30, classesAttended: 21 },
          { month: 'Feb', percentage: 68, classesHeld: 30, classesAttended: 20 },
          { month: 'Mar', percentage: 70, classesHeld: 28, classesAttended: 20 },
          { month: 'Apr', percentage: 71, classesHeld: 25, classesAttended: 18 },
        ],
        subjects: [
          { id: 'r4-1', code: 'IT2201', name: 'Algorithm Design', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 72, category: 'core' },
          { id: 'r4-2', code: 'IT2202', name: 'Computer Networks', credits: 4, grade: 'B', gradePoint: 7, attendancePercentage: 71, category: 'core' },
          { id: 'r4-3', code: 'IT2203', name: 'Web Technologies', credits: 4, grade: 'B+', gradePoint: 8, attendancePercentage: 74, category: 'core' },
          { id: 'r4-4', code: 'IT2204', name: 'Networks Lab', credits: 2, grade: 'A', gradePoint: 8.5, attendancePercentage: 78, category: 'lab' },
          { id: 'r4-5', code: 'MA2201', name: 'Probability & Statistics', credits: 4, grade: 'P', gradePoint: 5, attendancePercentage: 65, category: 'core' },
          { id: 'r4-6', code: 'IT2205', name: 'Software Engineering', credits: 4, grade: 'C', gradePoint: 6, attendancePercentage: 68, category: 'core' },
          { id: 'r4-7', code: 'IT2206', name: 'Web Tech Lab', credits: 2, grade: 'A+', gradePoint: 9, attendancePercentage: 80, category: 'lab' },
        ],
      },
    ],
  },
];
